spring:
  data:
    mongodb:
      uri: mongodb+srv://id:pw@mongodb.net/db?retryWrites=true&w=majority
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: CLIENT_ID
            client-secret: GOCSPX-CLIENT_SECRET
            scope:
              - profile
              - email
          github:
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            scope:
              - read:user
              - user:email
          naver:
            client-name: Naver
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-name: Kakao
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
              - profile_image

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: 8080
  frontend: "http://localhost:8123"
  default:
    user: "https://user_profile.png"

logging:
  level:
#    root: debug
    org.springframework.security.web.authentication.logout.LogoutFilter: ERROR
    org:
      springframework:

        security: debug

jwt:
  issuer: issuer
  secret_key:
  # openssl rand -hex 32
